# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06caae0b2e9abbb8df0b22ea92e7630406707e4816f0b1a85c07b4b3a46f311e1b7a8b3119b461f6c2d319a1b82760e400b73b11844288e5f5fb6188476df29d

test:
  secret_key_base: 43ea1ec617cac6b21ad305af276fa1eac2cf7e9490b9caecd03aa8c76056b03c59fa665a4210f5c401e6d1570d98b289694e2658a1e99f32598e831581cd8d8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
